sudo: required
services:
    - docker
before_install:
    - docker build -t ramenator/multi-docker-client-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true ramenator/multi-docker-client-test npm test

after_success:
    - docker build -t ramenator/multi-docker-client ./client
    - docker build -t ramenator/multi-docker-server ./server
    - docker build -t ramenator/multi-docker-nginx ./nginx
    - docker build -t ramenator/multi-docker-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login-u "$DOCKER_ID" --password-stdin
    - docker push ramenator/multi-docker-client
    - docker push ramenator/multi-docker-nginx
    - docker push ramenator/multi-docker-server
    - docker push ramenator/multi-docker-worker